name: Validate crate

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: giancosta86/aurora-github/actions/validate-rust-crate@b2.0.0
