name: Validate crate

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #- uses: giancosta86/aurora-github/actions/validate-rust-crate@v2

      - id: detector
        uses: giancosta86/aurora-github/actions/get-branch-version@b2.0.0

      - run: |
          branch="${{ steps.detector.outputs.branch }}"
          version="${{ steps.detector.outputs.version }}"

          echo "Detected version '$version' from branch '$branch'"
